// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"architecture.mdx": () => import("../content/docs/architecture.mdx?collection=docs"), "core-concepts.mdx": () => import("../content/docs/core-concepts.mdx?collection=docs"), "crank-runbook.mdx": () => import("../content/docs/crank-runbook.mdx?collection=docs"), "error-reference.mdx": () => import("../content/docs/error-reference.mdx?collection=docs"), "escrow.mdx": () => import("../content/docs/escrow.mdx?collection=docs"), "getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "lifecycle.mdx": () => import("../content/docs/lifecycle.mdx?collection=docs"), "reserve.mdx": () => import("../content/docs/reserve.mdx?collection=docs"), "rotation-lifecycle.mdx": () => import("../content/docs/rotation-lifecycle.mdx?collection=docs"), "api-reference/claimPayout.mdx": () => import("../content/docs/api-reference/claimPayout.mdx?collection=docs"), "api-reference/contribute.mdx": () => import("../content/docs/api-reference/contribute.mdx?collection=docs"), "api-reference/createAccount.mdx": () => import("../content/docs/api-reference/createAccount.mdx?collection=docs"), "api-reference/createGroup.mdx": () => import("../content/docs/api-reference/createGroup.mdx?collection=docs"), "api-reference/deleteAccount.mdx": () => import("../content/docs/api-reference/deleteAccount.mdx?collection=docs"), "api-reference/deleteGroup.mdx": () => import("../content/docs/api-reference/deleteGroup.mdx?collection=docs"), "api-reference/distributePayout.mdx": () => import("../content/docs/api-reference/distributePayout.mdx?collection=docs"), "api-reference/exitGroup.mdx": () => import("../content/docs/api-reference/exitGroup.mdx?collection=docs"), "api-reference/extendGraceWindow.mdx": () => import("../content/docs/api-reference/extendGraceWindow.mdx?collection=docs"), "api-reference/joinGroup.mdx": () => import("../content/docs/api-reference/joinGroup.mdx?collection=docs"), "api-reference/nextCycle.mdx": () => import("../content/docs/api-reference/nextCycle.mdx?collection=docs"), "api-reference/startGroup.mdx": () => import("../content/docs/api-reference/startGroup.mdx?collection=docs"), "api-reference/terminateGroup.mdx": () => import("../content/docs/api-reference/terminateGroup.mdx?collection=docs"), "api-reference/updateAccount.mdx": () => import("../content/docs/api-reference/updateAccount.mdx?collection=docs"), "api-reference/updateGroup.mdx": () => import("../content/docs/api-reference/updateGroup.mdx?collection=docs"), "api-reference/updatePayoutCredential.mdx": () => import("../content/docs/api-reference/updatePayoutCredential.mdx?collection=docs"), }),
};
export default browserCollections;